sonar.projectKey=laboratorio-clinico-front
sonar.projectName=Laboratorio Clinico Front
sonar.projectVersion=1.0

# Credenciales
sonar.login=sqp_070314e466458b7e704af1ea2e7cac21d3a6ae56

# Fuentes
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.spec.ts,src/environments/**,src/main.ts,src/app/app.config.ts,src/app/app.routes.ts,**/*.html,**/*.css

# Pruebas
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

# Reporte de cobertura (VITAL)
sonar.typescript.lcov.reportPaths=coverage/laboratorio-clinico/lcov.info